### ISSUE TITLE
Static code analysis with Codacy

### ISSUE THREAD

**Issue by Hunthomas** [BME-MIT-IET/srsh2-iet-2018#2]
Initial static code analysis result:
![image](https://user-images.githubusercontent.com/25303521/39419937-6f459f22-4c62-11e8-855c-655e6d0bc8d1.png)
![image](https://user-images.githubusercontent.com/25303521/39419956-7f21dd0c-4c62-11e8-94a4-ce049454c01c.png)

**Comment by Hunthomas** [comment]
Unused codes removed in commit https://github.com/BME-MIT-IET/srsh2-iet-2018/commit/4ab6bebb7c4c020e9faf70c6abfeaa5bb1e6725f. 
![image](https://user-images.githubusercontent.com/25303521/39421034-83286de4-4c67-11e8-8033-dec9f353c39e.png)

**Comment by Hunthomas** [comment]
Fixed some code style issues in commit https://github.com/BME-MIT-IET/srsh2-iet-2018/commit/57a6fc9a5b6e1313ff137fb9c7b86b4892ede2c8.
![image](https://user-images.githubusercontent.com/25303521/39421517-b7f97c46-4c69-11e8-9c13-59021fbb5718.png)

**Comment by szekelybalint** [comment]
Fixed some code style issues.
https://github.com/BME-MIT-IET/srsh2-iet-2018/commit/7365662e56ec169e02ad66eacca5cea7371039ee

**Comment by Hunthomas** [comment]
Statistics now after the previous commits:
![image](https://user-images.githubusercontent.com/25303521/39676398-775d6368-516a-11e8-82b2-845cfb632504.png)

Fixed some more serious code style issues in commits https://github.com/BME-MIT-IET/srsh2-iet-2018/commit/91414f8dbe51843088452b9046eb6713d89fbc13 and https://github.com/BME-MIT-IET/srsh2-iet-2018/commit/0811198725d76a82a0a80567f412f4085d6f0ee5
> e.g.: Avoid long parameter lists.
https://github.com/BME-MIT-IET/srsh2-iet-2018/blob/484a31bf9136676c14328671f3b797dc0eb9bbc4/src/eu/geoknow/athenarc/triplegeo/wkt/RdbToRdf.java#L286-L288

After these commits the Codacy result is this:
![image](https://user-images.githubusercontent.com/25303521/39676620-437d3f92-516e-11e8-9221-0d7bd223e7ed.png)
![image](https://user-images.githubusercontent.com/25303521/39676622-53543592-516e-11e8-8ad0-52076b2168f2.png)

Fixing the remaining issues found by Codacy would require serious restructuring of the code. Plus, most of them are not even real issues.

**Comment by patmarton** [comment]
Issue has been reviewed. **Enhancement was successful.**
