### ISSUE TITLE
Manual code review

### ISSUE THREAD

**Issue by Hunthomas** [BME-MIT-IET/srsh2-iet-2018#3]

**Comment by Hunthomas** [comment]
I found an SQL query where the query is concatenated from strings.
https://github.com/BME-MIT-IET/srsh2-iet-2018/blob/6c4b3794ed5ee7dd5aeef4ae6aae186b4cd2e2c6/src/eu/geoknow/athenarc/triplegeo/wkt/RdbToRdf.java#L284-L286

https://github.com/BME-MIT-IET/srsh2-iet-2018/blob/6c4b3794ed5ee7dd5aeef4ae6aae186b4cd2e2c6/src/eu/geoknow/athenarc/triplegeo/wkt/RdbToRdf.java#L305-L347

**Comment by patmarton** [comment]
Using switch statements (switch-case) violates the Open-Closed Principle. The design should be improved by using polymorphism, Visitor design pattern or Factory methods, if possible. 
https://github.com/BME-MIT-IET/srsh2-iet-2018/blob/484a31bf9136676c14328671f3b797dc0eb9bbc4/src/eu/geoknow/athenarc/triplegeo/wkt/RdbToRdf.java#L176-L201

**Comment by szekelybalint** [comment]
SQL vulnerability should be the number one priority, as string concatenation in queries is very bad practice.
If further extensions, versions are expected, the implementation of a design pattern should be considered as well instead of the switch-case statements.
Findings were reviewed.
