### ISSUE TITLE
Unit Testing with JUnit

### ISSUE THREAD

**Issue by zekiraly** [BME-MIT-IET/srsh2-iet-2018#4]
The project does not include any unit tests.
- Prepare the Ant Infrastructure: make a test target which depends on the compile target
- Create unit tests

**Comment by zekiraly** [comment]
Created [a Pull Request](https://github.com/BME-MIT-IET/srsh2-iet-2018/pull/5)

The changes are the following:
- Created an ant task for tests in build.xml (you can run it with "ant test")
- Moved the test directory content to manual_test directory, because I wanted the test classes to be "paralell" with the source classes
- Under test directory, I created unit tests for the main classes, the connectors, and the utils
- I had to add Mockito and Powermockito and it's dependencies to the libs
- Made minimal changes to Connector constructors to allow dependency injection

Additional comments:
- Travis finished successfully on tests
- I had to reimport the project in eclipse to make it recognise the test directory as source folder.

**Comment by Hunthomas** [comment]
https://github.com/BME-MIT-IET/srsh2-iet-2018/pull/5 contains high quality unit tests.
Changes approved. Pull request merged in commit https://github.com/BME-MIT-IET/srsh2-iet-2018/commit/520565c8003b73444c427642bf3cf24653b22ebe.
